import Foundation

/// The five courses, drawn out. Every one is thirteen tiles wide with the vault at the top and
/// the hoard at the bottom, and is built from the same few traps.
enum Courses {
    static func blueprint(_ kind: MissionKind) -> Blueprint {
        switch kind {
        case .greatHall: return greatHall
        case .cellars: return cellars
        case .armoury: return armoury
        case .battlements: return battlements
        case .crypt: return crypt
        }
    }

    /// Blades and a floor that will not hold. The three blades below the vault swing a third of
    /// a beat apart, so there is one pace that walks straight through them.
    private static let greatHall = Blueprint(rows: [
        "#############",
        "#VVVVVVVVVVV#",
        "#VVVVVVVVVVV#",
        "#...........#",
        "#.....B.....#",
        "#...........#",
        "a1.........1#",
        "#...........#",
        "#2.........2b",
        "#...........#",
        "c3.........3#",
        "#...........#",
        "#...........#",
        "#..##...##..#",
        "#...........*",
        "#~~~~~.~~~~~#",
        "#~~~~~.~~~~~#",
        "#...........#",
        "#.....B.....#",
        "#...........#",
        ",...........#",
        "#4....4.....#",
        "d...........#",
        "#.....5....5#",
        "#...........e",
        "#...........#",
        "#..##...##..#",
        "#...........#",
        "#~~~.~~~.~~~#",
        "#...........#",
        "*...........#",
        "#6.........6#",
        "#...........f",
        "#...........#",
        "#.....B.....#",
        "#...........#",
        "#...........#",
        "#HHHHHHHHHHH#",
        "#HHHHHHHHHHH#",
        "#############",
    ], traps: [
        Trap(kind: .blade, mark: "1", lever: "a", period: 2.4),
        Trap(kind: .blade, mark: "2", lever: "b", period: 2.4, offset: 0.8),
        Trap(kind: .blade, mark: "3", lever: "c", period: 2.4, offset: 1.6),
        Trap(kind: .blade, mark: "4", lever: "d", period: 1.7, act: 1),
        Trap(kind: .blade, mark: "5", lever: "e", period: 1.7, act: 1, offset: 0.85),
        Trap(kind: .blade, mark: "6", lever: "f", period: 2.6, offset: 0.5),
    ])

    /// Barrels. The left-hand lane below the vault is short and straight and has barrels coming
    /// down it; the right-hand one winds and has none.
    private static let cellars = Blueprint(rows: [
        "#############",
        "#VVVVVVVVVVV#",
        "#VVVVVVVVVVV#",
        "#...........#",
        "#.....B.....#",
        "#...........#",
        "a123#.......#",
        "#...#.......#",
        "#...####....#",
        "#...#.......#",
        "#...#...#####",
        "#...#.......#",
        "#...####....*",
        "#...#.......#",
        "#...#...#####",
        "#...#.......#",
        "#...#.......#",
        "b123#.......#",
        "#...........#",
        "#.....B.....#",
        "#...........#",
        "#~~~~~~~~~~~#",
        "#~~.~~~~.~~~#",
        "#...........#",
        ",...........#",
        "#..4.....5..#",
        "#...........#",
        "#..~~...~~..#",
        "#...........c",
        "#...........#",
        "#.....#.....#",
        "#...........#",
        "#..4.....5..#",
        "*...........#",
        "#.....B.....#",
        "#...........#",
        "#...........#",
        "#HHHHHHHHHHH#",
        "#HHHHHHHHHHH#",
        "#############",
    ], traps: [
        Trap(kind: .barrel, mark: "1", lever: "a", period: 3.9),
        Trap(kind: .barrel, mark: "2", period: 3.9, offset: 1.3),
        Trap(kind: .barrel, mark: "3", lever: "b", period: 3.9, offset: 2.6),
        Trap(kind: .barrel, mark: "4", lever: "c", period: 3.4, act: 1),
        Trap(kind: .barrel, mark: "5", period: 3.4, act: 1, offset: 1.7),
    ])

    /// Spikes and darts. The darts are set off by plates two paces short of them, so it is
    /// usually somebody else's foot that fires the row you are standing in.
    private static let armoury = Blueprint(rows: [
        "#############",
        "#VVVVVVVVVVV#",
        "#VVVVVVVVVVV#",
        "#...........#",
        "#.....B.....#",
        "#...........#",
        "#1.....2....#",
        "#....1.....2#",
        "#...........#",
        "a3.........3#",
        "#...........#",
        "#...x...x...#",
        "#...........#",
        "#..#..#..#..#",
        "#...........*",
        "#4..........#",
        "#....4.5....#",
        "#..........5#",
        "#...........#",
        "#.....B.....#",
        "#...........#",
        "#6.........6b",
        "#...........#",
        "#.y...y...y.#",
        "#...........#",
        ",...........#",
        "c7.........7#",
        "#...........#",
        "#..z.....z..#",
        "#...........#",
        "#8....8.....#",
        "#.....9....9#",
        "#...........#",
        "*...........#",
        "#.....B.....#",
        "#...........#",
        "#...........#",
        "#HHHHHHHHHHH#",
        "#HHHHHHHHHHH#",
        "#############",
    ], traps: [
        Trap(kind: .spikes, mark: "1", period: 2.8),
        Trap(kind: .spikes, mark: "2", period: 2.8, offset: 1.4),
        Trap(kind: .darts, mark: "3", lever: "a", plate: "x"),
        Trap(kind: .spikes, mark: "4", period: 2.6, offset: 0.4),
        Trap(kind: .spikes, mark: "5", period: 2.6, offset: 1.7),
        Trap(kind: .darts, mark: "6", lever: "b", plate: "y"),
        Trap(kind: .darts, mark: "7", lever: "c", plate: "z", act: 1),
        Trap(kind: .spikes, mark: "8", period: 2.4, act: 1),
        Trap(kind: .spikes, mark: "9", period: 2.4, act: 1, offset: 1.2),
    ])

    /// Gusts on a wall-walk with nothing at its edges but the odd merlon.
    private static let battlements = Blueprint(rows: [
        "#############",
        "#VVVVVVVVVVV#",
        "#VVVVVVVVVVV#",
        "#...........#",
        "#.....B.....#",
        "#...........#",
        " ........... ",
        " 1.......... ",
        "#...........#",
        " ..........1 ",
        " ........... ",
        "#....~~~....#",
        " ...~~~~~... ",
        " ........... ",
        "a..2.....3.. ",
        " ........... ",
        " ........... ",
        "#...........*",
        " .....B..... ",
        " ........... ",
        " 4.......... ",
        "#...........#",
        " ..........4 ",
        " ..2.....3.. ",
        " ........... ",
        "#..~~~.~~~..#",
        " ..~~~.~~~.. ",
        " ........... ",
        ",........... ",
        " 5.......... ",
        "#...........b",
        " ..........5 ",
        " ........... ",
        "#...........#",
        "#.....B.....#",
        "#...........#",
        "#...........#",
        "#HHHHHHHHHHH#",
        "#HHHHHHHHHHH#",
        "#############",
    ], traps: [
        Trap(kind: .gust, mark: "1", period: 5.5, offset: 2, push: Vec2(120, 0)),
        Trap(kind: .barrel, mark: "2", lever: "a", period: 4.2),
        Trap(kind: .barrel, mark: "3", period: 4.2, act: 1, offset: 2.1),
        Trap(kind: .gust, mark: "4", period: 5.5, offset: 4, push: Vec2(-120, 0)),
        Trap(kind: .gust, mark: "5", lever: "b", period: 5, act: 1, push: Vec2(120, 0)),
    ])

    /// Flame and blades by candlelight. Nobody can see far, and a doused sconce leaves a third of it black.
    private static let crypt = Blueprint(rows: [
        "#############",
        "#VVVVVVVVVVV#",
        "#VVVVVVVVVVV#",
        "#...........#",
        "#.....B.....#",
        "#...........#",
        "#1....1.....#",
        "#...........#",
        "#.....2....2a",
        "#...........#",
        "#..##...##..#",
        "#...........*",
        "#..##...##..#",
        "#...........#",
        "b3.........3#",
        "#...........#",
        "#4...4......#",
        "#...........#",
        "#.....B.....#",
        "*...........#",
        "#...........#",
        "#..#..#..#..#",
        "#...........#",
        "#......5...5#",
        "#...........#",
        "#6....6.....c",
        "#...........#",
        ",...........#",
        "#7.........7#",
        "#...........#",
        "#..##...##..#",
        "#...........*",
        "#...........#",
        "#...........#",
        "#.....B.....#",
        "#...........#",
        "#...........#",
        "#HHHHHHHHHHH#",
        "#HHHHHHHHHHH#",
        "#############",
    ], traps: [
        Trap(kind: .flame, mark: "1", period: 3),
        Trap(kind: .flame, mark: "2", lever: "a", period: 3, offset: 1.5),
        Trap(kind: .blade, mark: "3", lever: "b", period: 2.6),
        Trap(kind: .flame, mark: "4", period: 2.8, act: 1),
        Trap(kind: .flame, mark: "5", period: 3.2, offset: 0.7),
        Trap(kind: .flame, mark: "6", lever: "c", period: 3.2, offset: 2.3),
        Trap(kind: .blade, mark: "7", period: 2.2, act: 1, offset: 1),
    ], vision: 110)
}
